# Generated by Django 4.2.16 on 2026-03-26 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PointOfInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="დასახელება")),
                (
                    "description",
                    models.TextField(verbose_name="აღწერა (50-120 სიტყვა)"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="pois/", verbose_name="ფოტო"
                    ),
                ),
                (
                    "open_hours",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="სამუშაო საათები"
                    ),
                ),
                (
                    "poi_type",
                    models.CharField(
                        choices=[
                            ("historical", "ისტორიული"),
                            ("tourist", "ტურისტული ადგილი"),
                            ("museum", "მუზეუმი"),
                            ("park", "პარკი"),
                            ("food", "კვების ობიექტი"),
                            ("entertainment", "გასართობი ადგილი"),
                            ("partner", "პარტნიორი ბიზნესი"),
                        ],
                        max_length=50,
                        verbose_name="ლოკაციის ტიპი",
                    ),
                ),
                ("latitude", models.FloatField(verbose_name="Latitude (Y)")),
                ("longitude", models.FloatField(verbose_name="Longitude (X)")),
                (
                    "base_xp",
                    models.PositiveIntegerField(
                        default=50, verbose_name="გასაცემი XP ქულები"
                    ),
                ),
                (
                    "reward_badge_name",
                    models.CharField(
                        blank=True,
                        help_text="რა Skin/Badge შეიძლება მოგცეს (XP გარდა)",
                        max_length=100,
                    ),
                ),
                (
                    "google_maps_link",
                    models.URLField(blank=True, verbose_name="Google Maps ლინკი"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RedZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="ზონის სახელი (Scammer Area)"
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "radius_meters",
                    models.FloatField(default=100.0, verbose_name="რადიუსი მეტრებში"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("awarded_xp", models.PositiveIntegerField(default=0)),
                (
                    "poi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="maps.pointofinterest",
                    ),
                ),
            ],
            options={
                "verbose_name": "ჩექინი (Check-in)",
            },
        ),
    ]
