# Generated by Django 4.2.16 on 2026-03-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pointofinterest",
            name="audio_guide",
            field=models.FileField(
                blank=True, null=True, upload_to="audio/", verbose_name="აუდიო გიდი"
            ),
        ),
    ]
