# Generated by Django 4.2.16 on 2026-03-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0003_pointofinterest_audio_guide"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pointofinterest",
            name="latitude",
            field=models.FloatField(default=41.7151, verbose_name="Latitude (Y)"),
        ),
        migrations.AlterField(
            model_name="pointofinterest",
            name="longitude",
            field=models.FloatField(default=44.8271, verbose_name="Longitude (X)"),
        ),
        migrations.AlterField(
            model_name="redzone",
            name="latitude",
            field=models.FloatField(default=41.7151),
        ),
        migrations.AlterField(
            model_name="redzone",
            name="longitude",
            field=models.FloatField(default=44.8271),
        ),
    ]
