# Generated by Django 6.0.5 on 2026-07-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0004_alter_pointofinterest_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pointofinterest",
            name="audio_guide_en",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="audio/",
                verbose_name="Audio Guide (EN)",
            ),
        ),
        migrations.AddField(
            model_name="pointofinterest",
            name="description_en",
            field=models.TextField(blank=True, verbose_name="Description (EN)"),
        ),
        migrations.AddField(
            model_name="pointofinterest",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Name (EN)"
            ),
        ),
        migrations.AddField(
            model_name="pointofinterest",
            name="open_hours_en",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Open Hours (EN)"
            ),
        ),
        migrations.AddField(
            model_name="redzone",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Zone Name (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="pointofinterest",
            name="audio_guide",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="audio/",
                verbose_name="აუდიო გიდი (KA)",
            ),
        ),
        migrations.AlterField(
            model_name="pointofinterest",
            name="description",
            field=models.TextField(verbose_name="აღწერა (KA)"),
        ),
        migrations.AlterField(
            model_name="pointofinterest",
            name="name",
            field=models.CharField(max_length=200, verbose_name="დასახელება (KA)"),
        ),
        migrations.AlterField(
            model_name="pointofinterest",
            name="open_hours",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="სამუშაო საათები (KA)"
            ),
        ),
        migrations.AlterField(
            model_name="redzone",
            name="name",
            field=models.CharField(max_length=100, verbose_name="ზონის სახელი (KA)"),
        ),
    ]
