# Generated by Django 6.0.5 on 2026-08-04 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_alter_userinventory_options_and_more"),
        ("maps", "0005_pointofinterest_audio_guide_en_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="checkin",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="pointofinterest",
            name="reward_badge_name",
        ),
        migrations.AddField(
            model_name="pointofinterest",
            name="reward_badge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pois_rewarded",
                to="inventory.badge",
                verbose_name="საპრიზო ბეჯი",
            ),
        ),
        migrations.AddField(
            model_name="pointofinterest",
            name="reward_skin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pois_rewarded",
                to="inventory.skin",
                verbose_name="საპრიზო სკინი",
            ),
        ),
        migrations.AlterField(
            model_name="pointofinterest",
            name="latitude",
            field=models.FloatField(
                db_index=True, default=41.7151, verbose_name="Latitude (Y)"
            ),
        ),
        migrations.AlterField(
            model_name="pointofinterest",
            name="longitude",
            field=models.FloatField(
                db_index=True, default=44.8271, verbose_name="Longitude (X)"
            ),
        ),
        migrations.AlterField(
            model_name="redzone",
            name="latitude",
            field=models.FloatField(db_index=True, default=41.7151),
        ),
        migrations.AlterField(
            model_name="redzone",
            name="longitude",
            field=models.FloatField(db_index=True, default=44.8271),
        ),
        migrations.AddConstraint(
            model_name="checkin",
            constraint=models.UniqueConstraint(
                fields=("user", "poi"), name="unique_user_poi_checkin"
            ),
        ),
    ]
