# Generated by Django 6.0.5 on 2026-08-11 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EcoMission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mission_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Mission ID"
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Title (KA)")),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Title (EN)"
                    ),
                ),
                (
                    "location_name",
                    models.CharField(max_length=300, verbose_name="Location Name"),
                ),
                ("latitude", models.FloatField(db_index=True)),
                ("longitude", models.FloatField(db_index=True)),
                (
                    "geofence_radius_m",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Geofence Radius (m)"
                    ),
                ),
                (
                    "task_description",
                    models.TextField(verbose_name="Task Description (KA)"),
                ),
                (
                    "task_description_en",
                    models.TextField(blank=True, verbose_name="Task Description (EN)"),
                ),
                (
                    "ar_object",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="AR Object Filename",
                    ),
                ),
                (
                    "requirements",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Requirements"
                    ),
                ),
                (
                    "reward_skin",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Reward Skin"
                    ),
                ),
                (
                    "reward_badge",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Reward Badge"
                    ),
                ),
                (
                    "reward_xp",
                    models.PositiveIntegerField(default=0, verbose_name="Reward XP"),
                ),
                (
                    "reward_points",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Reward Points"
                    ),
                ),
                (
                    "reward_discount",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Reward Discount",
                    ),
                ),
                (
                    "reward_notes",
                    models.TextField(blank=True, verbose_name="Reward Notes"),
                ),
                (
                    "buttons",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Action Buttons"
                    ),
                ),
                (
                    "campaign_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Campaign Start"
                    ),
                ),
                (
                    "campaign_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Campaign End"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Internal Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Eco Mission",
                "verbose_name_plural": "Eco Missions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Landmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ka", models.CharField(max_length=200, verbose_name="Name (KA)")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Name (EN)"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("historical", "Historical"), ("modern", "Modern")],
                        default="historical",
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(max_length=300, verbose_name="Address")),
                ("latitude", models.FloatField(db_index=True)),
                ("longitude", models.FloatField(db_index=True)),
            ],
            options={
                "verbose_name": "Landmark",
                "verbose_name_plural": "Landmarks",
                "ordering": ["name_ka"],
            },
        ),
        migrations.CreateModel(
            name="WasteType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "waste_type",
                    models.CharField(
                        choices=[
                            ("plastic", "Plastic"),
                            ("paper", "Paper"),
                            ("glass", "Glass"),
                            ("metal", "Metal"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "qr_code_value",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="QR Code Value"
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waste_types",
                        to="eco_missions.ecomission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Waste Type QR",
                "verbose_name_plural": "Waste Type QRs",
            },
        ),
        migrations.CreateModel(
            name="UserMissionProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("qr_scanned_count", models.PositiveIntegerField(default=0)),
                ("photo_uploaded", models.BooleanField(default=False)),
                (
                    "gps_points_visited",
                    models.JSONField(
                        blank=True, default=list, verbose_name="GPS Points Visited"
                    ),
                ),
                ("xp_earned", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="eco_missions.ecomission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mission_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Mission Progress",
                "verbose_name_plural": "User Mission Progress",
                "ordering": ["-started_at"],
                "unique_together": {("user", "mission")},
            },
        ),
    ]
