# Generated by Django 6.0.5 on 2026-08-18 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eco_missions", "0001_initial"),
        ("maps", "0006_alter_checkin_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="landmark",
            name="poi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="landmarks",
                to="maps.pointofinterest",
                verbose_name="დაკავშირებული POI",
            ),
        ),
    ]
