# Generated by Django 6.0.5 on 2026-07-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="ტექსტის იდენტიფიკატორი (Key)",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("auth", "ავტორიზაცია (Auth)"),
                            ("map", "რუკა & დეტალები (Map & Details)"),
                            ("profile", "პროფილი & ინვენტარი (Profile & Backpack)"),
                            ("store", "მაღაზია & პარტნიორები (Store & Coupons)"),
                            ("ai", "AI დაგეგმარება (AI Planner)"),
                            ("errors", "შეცდომები & ვალიდაცია (Errors & Val)"),
                        ],
                        default="map",
                        max_length=20,
                        verbose_name="კატეგორია",
                    ),
                ),
                ("text_ka", models.TextField(verbose_name="ქართული ტექსტი (KA)")),
                ("text_en", models.TextField(verbose_name="ინგლისური ტექსტი (EN)")),
            ],
            options={
                "verbose_name": "ინტერფეისის თარგმანი",
                "verbose_name_plural": "🆎 ინტერფეისის თარგმანები (Localization)",
                "ordering": ["category", "key"],
            },
        ),
        migrations.CreateModel(
            name="ARTutorialStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step_number",
                    models.PositiveIntegerField(default=1, verbose_name="ნაბიჯი (#)"),
                ),
                (
                    "target_action",
                    models.CharField(
                        choices=[
                            ("look_around", "ტელეფონის ტრიალი (Look Around)"),
                            ("tap_poi", "ობიექტზე კლიკი (Tap POI)"),
                            ("checkin", "ჩექინის დასრულება (Checkin)"),
                        ],
                        default="look_around",
                        max_length=30,
                        verbose_name="სამიზნე მოქმედება",
                    ),
                ),
                ("instruction_ka", models.TextField(verbose_name="ინსტრუქცია (KA)")),
                (
                    "instruction_en",
                    models.TextField(blank=True, verbose_name="Instruction (EN)"),
                ),
                (
                    "lottie_animation_name",
                    models.CharField(
                        blank=True,
                        help_text="მაგ: scan_device, success_confetti",
                        max_length=100,
                        verbose_name="Lottie ანიმაცია",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="აქტიურია"),
                ),
            ],
            options={
                "verbose_name": "AR ტუტორიალის ნაბიჯი",
                "verbose_name_plural": "🕶️ AR ტუტორიალის ნაბიჯები",
                "ordering": ["step_number"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="სათაური (KA)"),
                ),
                ("description", models.TextField(verbose_name="აღწერა (KA)")),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Title (EN)"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description (EN)"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="onboarding/",
                        verbose_name="სლაიდის სურათი",
                    ),
                ),
                (
                    "step_number",
                    models.PositiveIntegerField(default=1, verbose_name="ნაბიჯი (#)"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="აქტიურია"),
                ),
            ],
            options={
                "verbose_name": "ონბორდინგ სლაიდი",
                "verbose_name_plural": "📱 ონბორდინგ სლაიდები",
                "ordering": ["step_number"],
            },
        ),
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "checkin_radius_meters",
                    models.FloatField(
                        default=40.0, verbose_name="ჩექინის რადიუსი (მეტრებში)"
                    ),
                ),
                (
                    "referral_bonus_xp",
                    models.PositiveIntegerField(
                        default=100, verbose_name="მოწვევის ბონუსი (XP)"
                    ),
                ),
                (
                    "referral_bonus_coins",
                    models.PositiveIntegerField(
                        default=50, verbose_name="მოწვევის ბონუსი (Coins)"
                    ),
                ),
                (
                    "app_maintenance_mode",
                    models.BooleanField(
                        default=False, verbose_name="ტექნიკური შესვენების რეჟიმი"
                    ),
                ),
                (
                    "min_app_version",
                    models.CharField(
                        default="1.0.0",
                        max_length=20,
                        verbose_name="მინიმალური ვერსია (საჭირო)",
                    ),
                ),
                (
                    "app_name_ka",
                    models.CharField(
                        default="თრეველგო",
                        max_length=100,
                        verbose_name="აპლიკაციის სახელი (KA)",
                    ),
                ),
                (
                    "app_name_en",
                    models.CharField(
                        default="TravelGo", max_length=100, verbose_name="App Name (EN)"
                    ),
                ),
                (
                    "maintenance_message_ka",
                    models.TextField(
                        default="მიმდინარეობს ტექნიკური სამუშაოები",
                        verbose_name="შეტყობინება შესვენებაზე (KA)",
                    ),
                ),
                (
                    "maintenance_message_en",
                    models.TextField(
                        default="Under maintenance",
                        verbose_name="Maintenance Message (EN)",
                    ),
                ),
            ],
            options={
                "verbose_name": "აპლიკაციის პარამეტრი",
                "verbose_name_plural": "⚙️ აპლიკაციის პარამეტრები (გლობალური)",
            },
        ),
    ]
