# Generated by Django 4.2.16 on 2026-03-26 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsProxy",
            fields=[],
            options={
                "verbose_name": "მოგზაური (სტატისტიკა)",
                "verbose_name_plural": "პლატფორმის ანალიტიკა (Dashboard)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.customuser",),
        ),
        migrations.AddField(
            model_name="customuser",
            name="referral_code",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                unique=True,
                verbose_name="უნიკალური კოდი",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invited_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ვინ მოიწვია",
            ),
        ),
    ]
