# Generated by Django 4.2.16 on 2026-03-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_analyticsproxy_customuser_referral_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar_clothing",
            field=models.CharField(
                default="basic_tshirt", max_length=50, verbose_name="ტანსაცმელი"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="avatar_hair_style",
            field=models.CharField(
                default="short_black", max_length=50, verbose_name="თმის სტილი"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="avatar_skin_color",
            field=models.CharField(
                default="#FFDCB2", max_length=20, verbose_name="კანის ფერი (Hex)"
            ),
        ),
    ]
