# Generated by Django 6.0.5 on 2026-07-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_customuser_avatar_clothing_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="სათაური")),
                ("description", models.TextField(verbose_name="აღწერა")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="onboarding/",
                        verbose_name="სლაიდის სურათი",
                    ),
                ),
                (
                    "step_number",
                    models.PositiveIntegerField(default=1, verbose_name="ნაბიჯი (#)"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="აქტიურია"),
                ),
            ],
            options={
                "verbose_name": "ონბორდინგ სლაიდი",
                "verbose_name_plural": "📱 ონბორდინგ სლაიდები",
                "ordering": ["step_number"],
            },
        ),
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "checkin_radius_meters",
                    models.FloatField(
                        default=40.0, verbose_name="ჩექინის რადიუსი (მეტრებში)"
                    ),
                ),
                (
                    "referral_bonus_xp",
                    models.PositiveIntegerField(
                        default=100, verbose_name="მოწვევის ბონუსი (XP)"
                    ),
                ),
                (
                    "referral_bonus_coins",
                    models.PositiveIntegerField(
                        default=50, verbose_name="მოწვევის ბონუსი (Coins)"
                    ),
                ),
                (
                    "app_maintenance_mode",
                    models.BooleanField(
                        default=False, verbose_name="ტექნიკური შესვენების რეჟიმი"
                    ),
                ),
                (
                    "min_app_version",
                    models.CharField(
                        default="1.0.0",
                        max_length=20,
                        verbose_name="მინიმალური ვერსია (საჭირო)",
                    ),
                ),
            ],
            options={
                "verbose_name": "აპლიკაციის პარამეტრი",
                "verbose_name_plural": "⚙️ აპლიკაციის პარამეტრები (გლობალური)",
            },
        ),
    ]
