# Generated by Django 6.0.5 on 2026-07-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_onboardingslide_systemconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="ტექსტის იდენტიფიკატორი (Key)",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("auth", "ავტორიზაცია (Auth)"),
                            ("map", "რუკა & დეტალები (Map & Details)"),
                            ("profile", "პროფილი & ინვენტარი (Profile & Backpack)"),
                            ("store", "მაღაზია & პარტნიორები (Store & Coupons)"),
                            ("ai", "AI დაგეგმარება (AI Planner)"),
                            ("errors", "შეცდომები & ვალიდაცია (Errors & Val)"),
                        ],
                        default="map",
                        max_length=20,
                        verbose_name="კატეგორია",
                    ),
                ),
                ("text_ka", models.TextField(verbose_name="ქართული ტექსტი (KA)")),
                ("text_en", models.TextField(verbose_name="ინგლისური ტექსტი (EN)")),
            ],
            options={
                "verbose_name": "ინტერფეისის თარგმანი",
                "verbose_name_plural": "🆎 ინტერფეისის თარგმანები (Localization)",
                "ordering": ["category", "key"],
            },
        ),
        migrations.AddField(
            model_name="onboardingslide",
            name="description_en",
            field=models.TextField(blank=True, verbose_name="Description (EN)"),
        ),
        migrations.AddField(
            model_name="onboardingslide",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Title (EN)"
            ),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="app_name_en",
            field=models.CharField(
                default="TravelGo", max_length=100, verbose_name="App Name (EN)"
            ),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="app_name_ka",
            field=models.CharField(
                default="თრეველგო",
                max_length=100,
                verbose_name="აპლიკაციის სახელი (KA)",
            ),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="maintenance_message_en",
            field=models.TextField(
                default="Under maintenance", verbose_name="Maintenance Message (EN)"
            ),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="maintenance_message_ka",
            field=models.TextField(
                default="მიმდინარეობს ტექნიკური სამუშაოები",
                verbose_name="შეტყობინება შესვენებაზე (KA)",
            ),
        ),
        migrations.AlterField(
            model_name="onboardingslide",
            name="description",
            field=models.TextField(verbose_name="აღწერა (KA)"),
        ),
        migrations.AlterField(
            model_name="onboardingslide",
            name="title",
            field=models.CharField(max_length=150, verbose_name="სათაური (KA)"),
        ),
    ]
