# Generated by Django 6.0.5 on 2026-07-03 09:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_apptranslation_onboardingslide_description_en_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AppTranslation",
        ),
        migrations.DeleteModel(
            name="OnboardingSlide",
        ),
        migrations.DeleteModel(
            name="SystemConfig",
        ),
    ]
