# Generated by Django 4.2.16 on 2026-03-26 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, verbose_name="კატეგორია (სასტუმრო, კაფე, Dental)"
                    ),
                ),
                (
                    "icon_name",
                    models.CharField(
                        blank=True, help_text="Flutter Icon Name", max_length=50
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="პარტნიორის დასახელება"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="partners_logos/"
                    ),
                ),
                (
                    "location_address",
                    models.CharField(max_length=255, verbose_name="მისამართი"),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "offer_percentage",
                    models.PositiveIntegerField(
                        default=5, verbose_name="ფასდაკლების % (ან ბონუსი)"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="შეთავაზების დეტალები"),
                ),
                (
                    "terms_and_conditions",
                    models.TextField(blank=True, verbose_name="წესები და პირობები"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partners",
                        to="partners.category",
                    ),
                ),
            ],
        ),
    ]
