# Generated by Django 4.2.16 on 2026-03-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="latitude",
            field=models.FloatField(default=41.7151),
        ),
        migrations.AlterField(
            model_name="partner",
            name="longitude",
            field=models.FloatField(default=44.8271),
        ),
    ]
