# Generated by Django 6.0.5 on 2026-07-03 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0002_alter_partner_latitude_alter_partner_longitude"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "კატეგორია",
                "verbose_name_plural": "პარტნიორის კატეგორიები",
            },
        ),
        migrations.AlterModelOptions(
            name="partner",
            options={"verbose_name": "პარტნიორი", "verbose_name_plural": "პარტნიორები"},
        ),
        migrations.CreateModel(
            name="DiscountCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        unique=True,
                        verbose_name="კუპონის კოდი",
                    ),
                ),
                (
                    "discount_pct",
                    models.PositiveIntegerField(
                        default=10, verbose_name="ფასდაკლება %"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "აქტიური"),
                            ("used", "გამოყენებული"),
                            ("expired", "ვადაგასული"),
                        ],
                        default="active",
                        max_length=10,
                        verbose_name="სტატუსი",
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True, null=True, verbose_name="ვარგისიანობის ვადა"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="შექმნის თარიღი"
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="გამოყენების თარიღი"
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupons",
                        to="partners.partner",
                        verbose_name="პარტნიორი",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupons",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="მომხმარებელი (ვისთვის)",
                    ),
                ),
            ],
            options={
                "verbose_name": "ფასდაკლების კუპონი",
                "verbose_name_plural": "ფასდაკლების კუპონები",
                "ordering": ["-created_at"],
            },
        ),
    ]
