# Generated by Django 6.0.5 on 2026-07-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0003_alter_category_options_alter_partner_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Category Name (EN)"
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="description_en",
            field=models.TextField(blank=True, verbose_name="Offer Details (EN)"),
        ),
        migrations.AddField(
            model_name="partner",
            name="location_address_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Address (EN)"
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Partner Name (EN)"
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="terms_and_conditions_en",
            field=models.TextField(blank=True, verbose_name="Terms & Conditions (EN)"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50, verbose_name="კატეგორია (KA)"),
        ),
        migrations.AlterField(
            model_name="partner",
            name="description",
            field=models.TextField(
                blank=True, verbose_name="შეთავაზების დეტალები (KA)"
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="location_address",
            field=models.CharField(max_length=255, verbose_name="მისამართი (KA)"),
        ),
        migrations.AlterField(
            model_name="partner",
            name="name",
            field=models.CharField(
                max_length=150, verbose_name="პარტნიორის დასახელება (KA)"
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="terms_and_conditions",
            field=models.TextField(blank=True, verbose_name="წესები და პირობები (KA)"),
        ),
    ]
