# Generated by Django 6.0.5 on 2026-08-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0004_category_name_en_partner_description_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="latitude",
            field=models.FloatField(db_index=True, default=41.7151),
        ),
        migrations.AlterField(
            model_name="partner",
            name="longitude",
            field=models.FloatField(db_index=True, default=44.8271),
        ),
    ]
