# Generated by Django 4.2.16 on 2026-03-26 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("maps", "0003_pointofinterest_audio_guide"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyQuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="ქვესთის სახელი"),
                ),
                ("description", models.TextField(verbose_name="აღწერა")),
                (
                    "reward_xp",
                    models.PositiveIntegerField(default=100, verbose_name="პრიზი (XP)"),
                ),
                (
                    "reward_coins",
                    models.PositiveIntegerField(
                        default=50, verbose_name="პრიზი (Coins)"
                    ),
                ),
                (
                    "required_checkins",
                    models.PositiveIntegerField(
                        default=1, verbose_name="საჭირო CheckIn-ების რ-ობა"
                    ),
                ),
                (
                    "date_active",
                    models.DateField(auto_now_add=True, verbose_name="ქვესთის თარიღი"),
                ),
                (
                    "target_poi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maps.pointofinterest",
                        verbose_name="სამიზნე ლოკაცია",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserQuestProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("progress", models.PositiveIntegerField(default=0)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quests.dailyquest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
