# Generated by Django 6.0.5 on 2026-07-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyquest",
            name="description_en",
            field=models.TextField(blank=True, verbose_name="Description (EN)"),
        ),
        migrations.AddField(
            model_name="dailyquest",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Quest Title (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="dailyquest",
            name="description",
            field=models.TextField(verbose_name="აღწერა (KA)"),
        ),
        migrations.AlterField(
            model_name="dailyquest",
            name="title",
            field=models.CharField(max_length=200, verbose_name="ქვესთის სახელი (KA)"),
        ),
    ]
