# Generated by Django 6.0.5 on 2026-07-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quests", "0002_dailyquest_description_en_dailyquest_title_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyquest",
            name="date_active",
            field=models.DateField(
                blank=True,
                default=None,
                help_text="დატოვეთ სადაც, რომლიც ქვესთი აქტიურია იქნება",
                null=True,
                verbose_name="ქვესთის თარიღი",
            ),
        ),
    ]
