# Generated by Django 6.0.5 on 2026-07-24 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0005_pointofinterest_audio_guide_en_and_more"),
        ("quests", "0003_alter_dailyquest_date_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.CharField(max_length=255, verbose_name="კითხვა (KA)"),
                ),
                (
                    "question_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Question (EN)"
                    ),
                ),
                (
                    "answer1",
                    models.CharField(max_length=150, verbose_name="პასუხი 1 (KA)"),
                ),
                (
                    "answer1_en",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Answer 1 (EN)"
                    ),
                ),
                (
                    "answer2",
                    models.CharField(max_length=150, verbose_name="პასუხი 2 (KA)"),
                ),
                (
                    "answer2_en",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Answer 2 (EN)"
                    ),
                ),
                (
                    "answer3",
                    models.CharField(max_length=150, verbose_name="პასუხი 3 (KA)"),
                ),
                (
                    "answer3_en",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Answer 3 (EN)"
                    ),
                ),
                (
                    "answer4",
                    models.CharField(max_length=150, verbose_name="პასუხი 4 (KA)"),
                ),
                (
                    "answer4_en",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Answer 4 (EN)"
                    ),
                ),
                (
                    "correct_index",
                    models.PositiveIntegerField(
                        default=0, help_text="0-დან 3-მდე (რომელი პასუხია სწორი)"
                    ),
                ),
                (
                    "poi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_questions",
                        to="maps.pointofinterest",
                        verbose_name="საინტერესო წერტილი (POI)",
                    ),
                ),
            ],
            options={
                "verbose_name": "ქვიზის კითხვა",
                "verbose_name_plural": "ქვიზის კითხვები",
            },
        ),
        migrations.CreateModel(
            name="UserPuzzleSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_submitted", models.DateTimeField(auto_now_add=True)),
                (
                    "poi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maps.pointofinterest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "პაზლის შედეგი",
                "verbose_name_plural": "პაზლების შედეგები",
            },
        ),
        migrations.CreateModel(
            name="UserQuizSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveIntegerField(default=0)),
                ("date_submitted", models.DateTimeField(auto_now_add=True)),
                (
                    "poi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maps.pointofinterest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ქვიზის შედეგი",
                "verbose_name_plural": "ქვიზების შედეგები",
            },
        ),
    ]
