# Generated by Django 6.0.5 on 2026-08-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quests", "0004_quizquestion_userpuzzlesubmission_userquizsubmission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyquest",
            name="date_active",
            field=models.DateField(
                blank=True,
                db_index=True,
                default=None,
                help_text="დატოვეთ სადაც, რომლიც ქვესთი აქტიურია იქნება",
                null=True,
                verbose_name="ქვესთის თარიღი",
            ),
        ),
    ]
