# Generated by Django 6.0.5 on 2026-08-18 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quests", "0005_alter_dailyquest_date_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userquestprogress",
            options={"verbose_name": "ქვესთის პროგრესი"},
        ),
        migrations.AddConstraint(
            model_name="userquestprogress",
            constraint=models.UniqueConstraint(
                fields=("user", "quest"), name="unique_user_quest_progress"
            ),
        ),
    ]
