# Generated by Django 6.0.5 on 2026-08-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quests", "0006_alter_userquestprogress_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquestprogress",
            name="is_claimed",
            field=models.BooleanField(default=False, verbose_name="პრიზი აღებულია"),
        ),
    ]
