# Generated by Django 6.0.5 on 2026-07-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="description_en",
            field=models.TextField(blank=True, verbose_name="Description (EN)"),
        ),
        migrations.AddField(
            model_name="badge",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Name (EN)"
            ),
        ),
        migrations.AddField(
            model_name="skin",
            name="description_en",
            field=models.TextField(blank=True, verbose_name="Description (EN)"),
        ),
        migrations.AddField(
            model_name="skin",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Skin Name (EN)"
            ),
        ),
        migrations.AddField(
            model_name="skin",
            name="region_unlock_en",
            field=models.CharField(
                blank=True,
                help_text="e.g. Adjara, Svaneti",
                max_length=100,
                verbose_name="Unlock Region (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="badge",
            name="description",
            field=models.TextField(verbose_name="აღწერა (KA)"),
        ),
        migrations.AlterField(
            model_name="badge",
            name="name",
            field=models.CharField(max_length=150, verbose_name="დასახელება (KA)"),
        ),
        migrations.AlterField(
            model_name="skin",
            name="description",
            field=models.TextField(verbose_name="აღწერა (KA)"),
        ),
        migrations.AlterField(
            model_name="skin",
            name="name",
            field=models.CharField(max_length=150, verbose_name="სკინის სახელი (KA)"),
        ),
        migrations.AlterField(
            model_name="skin",
            name="region_unlock",
            field=models.CharField(
                blank=True,
                help_text="მაგ: აჭარა, სვანეთი",
                max_length=100,
                verbose_name="განბლოკვის რეგიონი (KA)",
            ),
        ),
    ]
