# Generated by Django 6.0.5 on 2026-07-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_badge_description_en_badge_name_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="coin_price",
            field=models.PositiveIntegerField(default=0, verbose_name="ფასი მონეტებში"),
        ),
        migrations.AddField(
            model_name="badge",
            name="is_for_sale",
            field=models.BooleanField(default=False, verbose_name="იყიდება მაღაზიაში"),
        ),
        migrations.AddField(
            model_name="skin",
            name="coin_price",
            field=models.PositiveIntegerField(default=0, verbose_name="ფასი მონეტებში"),
        ),
        migrations.AddField(
            model_name="skin",
            name="is_for_sale",
            field=models.BooleanField(default=False, verbose_name="იყიდება მაღაზიაში"),
        ),
    ]
