# Generated by Django 6.0.5 on 2026-08-04 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory",
            "0003_badge_coin_price_badge_is_for_sale_skin_coin_price_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userinventory",
            options={"verbose_name": "ინვენტარი"},
        ),
        migrations.AddConstraint(
            model_name="userinventory",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("badge__isnull", False), ("skin__isnull", True)),
                    models.Q(("badge__isnull", True), ("skin__isnull", False)),
                    _connector="OR",
                ),
                name="inventory_badge_xor_skin",
            ),
        ),
        migrations.AddConstraint(
            model_name="userinventory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("badge__isnull", False)),
                fields=("user", "badge"),
                name="unique_user_badge",
            ),
        ),
        migrations.AddConstraint(
            model_name="userinventory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("skin__isnull", False)),
                fields=("user", "skin"),
                name="unique_user_skin",
            ),
        ),
    ]
