# Generated by Django 6.0.5 on 2026-07-03 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectWiki",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="დოკუმენტის სახელი"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("branding", "ბრენდინგი & დიზაინი (Branding & Design)"),
                            ("architecture", "არქიტექტურა & სტრუქტურა (Architecture)"),
                            ("general", "ზოგადი წესები (General Guidelines)"),
                        ],
                        default="general",
                        max_length=30,
                        verbose_name="კატეგორია",
                    ),
                ),
                (
                    "content",
                    models.TextField(verbose_name="შინაარსი (Markdown მხარდაჭერით)"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="განახლდა"),
                ),
            ],
            options={
                "verbose_name": "დოკუმენტი (Wiki)",
                "verbose_name_plural": "📖 პროექტის დოკუმენტაცია (Wiki)",
            },
        ),
        migrations.CreateModel(
            name="Sprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="ეტაპის დასახელება"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="აღწერა (მიზნები)"),
                ),
                ("start_date", models.DateField(verbose_name="დაწყების თარიღი")),
                ("end_date", models.DateField(verbose_name="დასრულების თარიღი")),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="დასრულებულია"),
                ),
            ],
            options={
                "verbose_name": "ეტაპი (Sprint)",
                "verbose_name_plural": "📅 ეტაპები და ვადები (Sprints & Roadmap)",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="დავალება")),
                (
                    "description",
                    models.TextField(verbose_name="დავალების დეტალები/აღწერა"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "დაბალი (Low)"),
                            ("medium", "საშუალო (Medium)"),
                            ("high", "მაღალი (High)"),
                            ("critical", "კრიტიკული (Critical) 🛑"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="პრიორიტეტი",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("backlog", "იდეა (Backlog)"),
                            ("todo", "გასაკეთებელი (Todo)"),
                            ("in_progress", "მიმდინარე (In Progress)"),
                            ("review", "შემოწმება (Review)"),
                            ("done", "შესრულებული (Done)"),
                        ],
                        default="todo",
                        max_length=20,
                        verbose_name="სტატუსი",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="შესრულების ვადა"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="პასუხისმგებელი პირი",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="project_manager.sprint",
                        verbose_name="ეტაპი (Sprint)",
                    ),
                ),
            ],
            options={
                "verbose_name": "დავალება (Task)",
                "verbose_name_plural": "📋 დავალებები (ClickUp Board)",
                "ordering": ["-priority", "due_date"],
            },
        ),
    ]
