# Generated by Django 6.0.5 on 2026-07-03 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "inventory",
            "0003_badge_coin_price_badge_is_for_sale_skin_coin_price_and_more",
        ),
        ("maps", "0005_pointofinterest_audio_guide_en_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChallengeInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, verbose_name="პირადი შეტყობინება"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "⏳ მოლოდინში"),
                            ("accepted", "✅ მიღებულია"),
                            ("declined", "❌ უარყოფილია"),
                            ("completed", "🏆 დასრულებულია"),
                            ("expired", "🕐 ვადაგასულია"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="სტატუსი",
                    ),
                ),
                (
                    "bonus_xp",
                    models.PositiveIntegerField(
                        default=25, verbose_name="ბონუს XP (გამარჯვებისთვის)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="შექმნის თარიღი"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ვადის გასვლის თარიღი"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="დასრულების თარიღი"
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_challenges",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="გამომგზავნი",
                    ),
                ),
                (
                    "poi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maps.pointofinterest",
                        verbose_name="სამიზნე ლოკაცია",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_challenges",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="მიმღები",
                    ),
                ),
            ],
            options={
                "verbose_name": "გამოწვევა",
                "verbose_name_plural": "⚔️ მეგობრების გამოწვევები",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FriendActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("checkin", "📍 ჩექინი"),
                            ("level_up", "⬆️ დონის ამაღლება"),
                            ("badge_earned", "🏅 ბეჯის მიღება"),
                            ("quest_completed", "✅ ქვესთის დასრულება"),
                            ("skin_unlocked", "🎨 სკინის განბლოკვა"),
                            ("joined", "🎉 შეუერთდა TravelGo-ს"),
                        ],
                        max_length=20,
                        verbose_name="ქმედების ტიპი",
                    ),
                ),
                (
                    "xp_earned",
                    models.PositiveIntegerField(default=0, verbose_name="მიღებული XP"),
                ),
                (
                    "new_level",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="ახალი დონე (level_up-ისთვის)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="თარიღი"),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.badge",
                        verbose_name="ბეჯი (badge_earned-ისთვის)",
                    ),
                ),
                (
                    "poi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="maps.pointofinterest",
                        verbose_name="ლოკაცია (ჩექინისთვის)",
                    ),
                ),
                (
                    "skin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.skin",
                        verbose_name="სკინი (skin_unlocked-ისთვის)",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="მომხმარებელი",
                    ),
                ),
            ],
            options={
                "verbose_name": "სოციალური ქმედება",
                "verbose_name_plural": "📰 სოციალური არხი (Feed)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "მოლოდინში"),
                            ("accepted", "დადასტურებული"),
                            ("blocked", "დაბლოკილი"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="სტატუსი",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="შექმნის თარიღი"
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_friend_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="გამომგზავნი",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_friend_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="მიმღები",
                    ),
                ),
            ],
            options={
                "verbose_name": "მეგობრობა",
                "verbose_name_plural": "🤝 მეგობრები",
                "ordering": ["-created_at"],
                "unique_together": {("from_user", "to_user")},
            },
        ),
    ]
