# Generated by Django 6.0.5 on 2026-08-04 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="friendship",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="challengeinvite",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="შექმნის თარიღი"
            ),
        ),
        migrations.AlterField(
            model_name="friendactivity",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="თარიღი"
            ),
        ),
        migrations.AddConstraint(
            model_name="friendship",
            constraint=models.UniqueConstraint(
                fields=("from_user", "to_user"), name="unique_friendship_direction"
            ),
        ),
        migrations.AddConstraint(
            model_name="friendship",
            constraint=models.CheckConstraint(
                condition=models.Q(("from_user", models.F("to_user")), _negated=True),
                name="prevent_self_friendship",
            ),
        ),
    ]
