# Generated by Django 6.0.5 on 2026-08-04 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0002_alter_friendship_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="challengeinvite",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_challenges",
                to=settings.AUTH_USER_MODEL,
                verbose_name="გამარჯვებული",
            ),
        ),
    ]
